version: '3'
services:
  app:
    build: .
    env_file: .env
    working_dir: /app
    command: rm -f tmp/pids/server.pid
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    environment:
      RAILS_LOG_TO_STDOUT: 'true'
    expose:
      - 8080
